#!/usr/bin/env sh
unset -v \
	initial_user_id \
	remove_initial_user_from_wheel \
	remove_wheel_group
[ -z "$VARFILE" ] || . "$VARFILE" || exit

systemctl daemon-reload || exit
{
	! systemctl -q is-active chrony.service ||
	systemctl restart chrony.service
} || exit

if [ -n "$initial_user_id" ]; then
	initial_user_name=$(
		getent passwd | LC_ALL=C awk -F: 'BEGIN {
			ARGC = 1
			uid = int(ARGV[1] + 0)
		}
		$3 == uid {
			if($1 == "") exit 1
			print $1
			exit
		}' "$initial_user_id"
	) || exit
else
	remove_initial_user_from_wheel=0
fi

[ "$remove_initial_user_from_wheel" = 1 ] && {
	delgroup -- "$initial_user_name" wheel
	case $? in
	0|2|3|6) ;;
	*) exit 1;;
	esac
}
[ "$remove_wheel_group" = 1 ] && {
	delgroup --system --only-if-empty wheel
	case $? in
	0|3|5) ;;
	*) exit 1;;
	esac
}

sysctl -p || exit

exit 0
