#!/usr/bin/env sh
is_group_exist() {
	getent group | LC_ALL=C awk -F: -- '
	BEGIN { ARGC = exit_code = 1 }
	$1 == ARGV[1] { exit_code = 0; exit }
	END { exit exit_code }' "$1"
}
is_user_in_group() {
	id -Gn -- "$1" | LC_ALL=C awk -- '
	BEGIN { ARGC = exit_code = 1 } {
		for(i = 1; i <= NF; i++) if($i == ARGV[1]) {
			exit_code = 0; exit
		}
	} END { exit exit_code }' "$2"
}


debcomp fs-diversify "$PREPDIR" || exit

# Checking for all POSIX utilities except mailx and lp
unset -v not_found_utils
old_ifs=$IFS; IFS=:
for util in \
	'[' at awk basename batch bc cat chgrp chmod chown cksum cmp comm cp \
	crontab csplit cut date dd diff dirname du echo ed env expand expr false \
	file find fold gencat getconf grep head iconv id join kill ln locale \
	localedef logger logname m4 man mkdir mkfifo mv newgrp nice nohup od paste \
	patch pathchk pax pr printf ps pwd renice rm rmdir sed sh sleep sort split \
	strings stty tabs tail tee test time touch tput tr true tsort tty uname \
	unexpand uniq uudecode uuencode wc write xargs
do
	is_util_exist=0
	for util_path in $PATH; do
		[ ":$util_path" = ":$CONFDIR" ] && continue
		[ -f "$util_path/$util" ] && [ -x "$util_path/$util" ] && {
			is_util_exist=1
			break
		}
	done
	[ $is_util_exist -eq 0 ] && not_found_utils=$not_found_utils', `'$util\'
done
IFS=$old_ifs
[ -n "$not_found_utils" ] && {
	debcomp log -e "checking POSIX utilities failed: $(printf %s "$not_found_utils" | sed 's/^, //') is not found in the system"
	exit 1
}

find \
	"$PREPDIR/etc/debcomp/userconf/common/preinst.d" \
	"$PREPDIR/etc/debcomp/userconf/common/postinst.d" \
	-type f -exec sh -c 'chmod +x "$0" || kill -INT "$PPID"' {} \; || exit

initial_user_id=$(
	. /etc/adduser.conf &&
	getent passwd | LC_ALL=C awk -F: 'BEGIN {
		ARGC = 1
		first_uid = int(ARGV[1] + 0)
	}
	$3 == first_uid {
		if($1 == "" || $6 !~ "^/") exit 1
		print $1 ":" $6 ":" $3
		exit
	}' "$FIRST_UID"
) || exit
[ -n "$initial_user_id" ] && {
	initial_user_name=${initial_user_id%%:*}; initial_user_id=${initial_user_id#*:}
	initial_user_home=${initial_user_id%%:*}; initial_user_id=${initial_user_id#*:}
}
debcomp setvar initial_user_id "$initial_user_id" || exit

is_group_exist wheel || {
	debcomp setvar remove_wheel_group 1 &&
	addgroup --system wheel
} || exit

chmod 700 "$HOME" || exit

[ -n "$initial_user_id" ] && {
	home_dir_mode=$(
		. "$PREPDIR/etc/adduser.conf" &&
		printf %s "$DIR_MODE"
	) || exit
	chmod "$home_dir_mode" "$initial_user_home" || exit

	[ $CONF_ADD_INITIAL_USER_TO_WHEEL -eq 1 ] && {
		is_user_in_group "$initial_user_name" wheel || {
			debcomp setvar remove_initial_user_from_wheel 1 &&
			adduser -- "$initial_user_name" wheel
		} || exit
	}
}

sysctl -p || exit

exit 0
